version: '3.8'

services:
  app:
    image: flask_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=user_app
    command: >
      sh -c "while ! nc -z db 3306; do sleep 1; done;
             python app.py"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_app
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql  # Adds persistence for MySQL data

volumes:
  db_data:  # Define the named volume for persistent MySQL data

